1주차 과제 업로드 합니다.
AndroidTutoring/Android_CleanArchitecture_Tutoring pull request #10
Opened 2022-02-03 13:09 UTC by DavidKwon7

2022-02-03 23:02 UTC, sageHabitus commented
1. Commit은 최대한 잘게 쪼개서 해주시고 기능단위로 해주시기 바랍니다.
2. Commit 메세지는 정확하게 무엇을 수정/삭제/추가 했는지 명시해주세요
3. Commit 할때는 반드시 리포맷, 테스트코드, 막 적은 코드는 배제해 주시고 정리해서 보내주셔야 합니다
4. 제 Comment에 대한 수정은 Commit을 하시고 관련 Commit 번호를 적어주시면 됩니다.(peer PR 참고)
4. 제가 peer review를 추가한 이유는 peer 코드를 보면서 자기 코드도 보완할 수 있기 때문입니다. peer 코드를 많이 참고해주세요.
5. 객체 할당이 무엇인지, 어떻게 이루어지는지, Activity 코드에서 지금 Repository가 왜 문제가 있는 코드인지 생각해보셔야 합니다.
6. 빠른 시간내에 하는 것도 능력이지만 자기가 무엇을 모르는지 빨리 파악하고 알맞게 질문하는 것도 매우 실무에서 중요한 능력입니다. 어차피 개발은 모든걸 알 수가 없고 항상 문제에 직면하기 때문입니다. 좀 더 분발해주세요.

2022-02-03 23:13 UTC, sageHabitus requested changes

2022-02-03 23:13 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/User.kt
> +                val url: String?)
nullable 하지않고 default값을 넣어주세요. nullable을 고수해야 한다쳐도 id는 nullable 하면 안됩니다.

2022-02-04 00:02 UTC, sageHabitus commented
PR 템플릿, Issue 템플릿 제대로 동작하나요?

2022-02-04 00:06 UTC, sageHabitus requested changes

2022-02-04 00:06 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/FavoriteAdapter.kt
> +class FavoriteAdapter(var postList: List<User>, val context: Context) :
1두개의 어뎁터를 하나로 통일해서 재활용해주세요.

2022-02-04 00:06 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/FavoriteAdapter.kt
> +class FavoriteAdapter(var postList: List<User>, val context: Context) :
Context를 넘기지말고 parent.context로 써주세요
생성자로 list를 넘기지말고 method로 넘겨주세요.

2022-02-04 00:06 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/FavoriteAdapter.kt
> +    inner class ViewHolder(view: View) : RecyclerView.ViewHolder(view) {
viewholder 분리

2022-02-04 00:06 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/User.kt
> +data class User(val name: String?,
지금 단계에서는 DTO를 통일해도 됩니다.

2022-02-04 00:23 UTC, sageHabitus requested changes

2022-02-04 00:23 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/SplashActivity.kt
> +    private lateinit var disposable: CompositeDisposable
disposable보다는 s를 붙이거나 좀 더 명확히 해주세요

2022-02-04 03:18 UTC, DavidKwon7 commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/MainActivity.kt
> +            .observeOn(AndroidSchedulers.mainThread())
3ec2481756da158748608dcafc0bcfae0dfaf61e 
수정 커밋 : mainthread 위치 변경

2022-02-04 03:48 UTC, DavidKwon7 commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/User.kt
> +                val url: String?)
e00e3abe8b2b01352890c04533cf12cb8387d6d5
수정 커밋 : data class User에서 nullable 제거

2022-02-04 04:40 UTC, DavidKwon7 commented
> PR 템플릿, Issue 템플릿 제대로 동작하나요?

2022-02-04 05:09 UTC, DavidKwon7 commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/SplashActivity.kt
> +    private lateinit var disposable: CompositeDisposable
063acd5cab866639fc9faef66ba296291180d1d2
수정 커밋 : disposable -> disposables 으로 변경

2022-02-04 06:17 UTC, DavidKwon7 commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/ProfileAdapter.kt
>      inner class ViewHolder(view: View) : RecyclerView.ViewHolder(view) {
4a7a5775f0ff030da1747bbb97f6208cbc47ab28
수정 커밋 : inner class -> class 로 변경

2022-02-04 06:48 UTC, DavidKwon7 commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/ProfileAdapter.kt
> +     interface OnItemClickListener{
f582b89bc039d926cb0e8f4395d093da124d7c9f
수정 커밋 : interface 위치 변경 & 제거

2022-02-04 06:52 UTC, DavidKwon7 commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/FavoriteAdapter.kt
> +    inner class ViewHolder(view: View) : RecyclerView.ViewHolder(view) {
4a7a5775f0ff030da1747bbb97f6208cbc47ab28
수정 커밋 : inner class -> class 로 변경

2022-02-04 07:14 UTC, DavidKwon7 commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/githubSource/remote/RemoteDataSourceImpl.kt
> +    val api = GithubRemoteRepoImpl.service
b1e6b50b387cec30563873befd2dc2de064e9ae3
수정 커밋 : 객체 생성 위치 변경

2022-02-04 07:22 UTC, DavidKwon7 commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/SplashActivity.kt
> +    override fun onDestroy() {
48e33f231f6aa6cb616ff05caf1d29b2e8267882
수정 커밋 : disposables 위치 변경

2022-02-04 07:26 UTC, DavidKwon7 commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/SplashActivity.kt
> +    private val backButtonSubject: Subject<Long> = BehaviorSubject.createDefault(0L)
311a1ffe08b058eb09b9b357c0a522917865fa74
수정 커밋 : BehaviorSubject 변경, 사용하지 않는 변수 제거

2022-02-04 07:33 UTC, DavidKwon7 commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/SplashActivity.kt
> +    private lateinit var disposable: CompositeDisposable
7e246df91ae7d72bac6fac47ae68fafd74bc7bc5
수정 커밋 : lateinit 제거

2022-02-04 07:35 UTC, DavidKwon7 commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/ProfileDetailActivity.kt
> +    lateinit var datas : List<User>
7e246df91ae7d72bac6fac47ae68fafd74bc7bc5
수정 커밋 : lateinit var datas 제거

2022-02-04 07:58 UTC, DavidKwon7 commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/ProfileAdapter.kt
> +     interface OnItemClickListener{
c65ff0de3d5d0c20a6e9347cc71b0a1788ce037d
재수정 커밋 : interface 새로 생성 및 이동

2022-02-04 09:03 UTC, DavidKwon7 commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/ProfileAdapter.kt
> +        this.githubRepos.clear()
88b9197ea6b34bc36958c9d2fff8d9e2436fba01
수정 커밋 : take method 추가

2022-02-04 15:46 UTC, DavidKwon7 commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/ProfileAdapter.kt
>              ContextCompat.startActivity(holder.itemView.context,intent,null)
67c63008c648b5a5b73236a5137d40ca7495f52e
수정 커밋 : adater 데이터 이동

2022-02-05 00:45 UTC, DavidKwon7 commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/githubRepository/GithubRepository.kt
> +    fun deleteFav() : Completable
ec20f63879aed6c1c3253c8571f9c37b2426646b
수정 커밋 : addFav, deleteFav 수정

2022-02-05 00:45 UTC, DavidKwon7 commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/githubSource/local/LocalDataSourceImpl.kt
> +    }
ec20f63879aed6c1c3253c8571f9c37b2426646b
수정 커밋 : addFav, deleteFav 수정

2022-02-05 00:46 UTC, DavidKwon7 commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/githubSource/local/LocalDataSource.kt
> +    fun deleteFav() :Completable
ec20f63879aed6c1c3253c8571f9c37b2426646b
수정 커밋 : addFav, deleteFav 수정

2022-02-05 00:46 UTC, DavidKwon7 commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/githubRepository/GetRepoRepository.kt
> +    val getRepoRemoteDataSource : RemoteDataSource = RemoteDataSourceImpl()
0e2e490714922d0a67c87cef7df702f34c7781a0
수정 커밋 : repository 변경 및 삭제

2022-02-05 00:47 UTC, DavidKwon7 commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/MainActivity.kt
> +            disposable.add(getRepoRepository.getRepos()
0e2e490714922d0a67c87cef7df702f34c7781a0
수정 커밋 : repository 변경 및 삭제

2022-02-05 00:47 UTC, DavidKwon7 commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/MainActivity.kt
> +                    repository.deleteFav()
0e2e490714922d0a67c87cef7df702f34c7781a0
수정 커밋 : repository 변경 및 삭제

2022-02-05 00:48 UTC, DavidKwon7 commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/githubSource/remote/RemoteDataSourceImpl.kt
> +        return api.getRepos("tkdgusl94")
0e2e490714922d0a67c87cef7df702f34c7781a0
수정 커밋 : repository 변경 및 삭제

2022-02-05 01:57 UTC, DavidKwon7 commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/FavoriteAdapter.kt
> +class FavoriteAdapter(var postList: List<User>, val context: Context) :
72e29c29cc6298bb42f37547ecafb1e6eacf9b97
수정 커밋 : FavoriteAdapter 수정

2022-02-05 04:02 UTC, sageHabitus approved these changes

2022-02-05 04:02 UTC, merged