3주차 과제입니다~!
AndroidTutoring/Android_CleanArchitecture_Tutoring pull request #17
Opened 2022-02-15 17:42 UTC by realizer12

3주차 과제 적용 내용
  1.  livedata 적용 
  2. databinding 적용

2022-02-17 08:39 UTC, DavidKwon7 reviewed
peer review 입니다

2022-02-17 08:39 UTC, DavidKwon7 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/adapter/UserListRvAdapter.kt
> +            binding.executePendingBindings()
결합된 데이터를 즉시 실행되어야 하는 경우 executePendingBindings() 메서드를 사용하는데, 이 때 onBindViewHolder에서 작업을 하는 것이라고 하네요. 

https://developer.android.com/topic/libraries/data-binding/generated-binding?hl=ko
여기에서 즉시결합, 고급 결합 부분 읽어보시면 도움이 될 것 같습니다!

2022-02-17 08:39 UTC, DavidKwon7 commented on 20220122_realizer12/presentation/src/main/res/layout/activity_main.xml
> +    </data>
data 안에 비어있으면 삭제해도 괜찮지 않을까요?

2022-02-17 08:39 UTC, DavidKwon7 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/viewmodel/MainViewModel.kt
>      val behaviorSubject = BehaviorSubject.createDefault(0L)
behaviorSubject 는 사용되지 않는 것으로 보이는데 삭제해도 괜찮지 않을까요??

2022-02-17 08:52 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/adapter/UserListRvAdapter.kt
> +            binding.executePendingBindings()
음 올려주신 링크에도  holder에 binding을 가져와  executePendingBindings를 사용하는데  혹시 어떤 부분때문에  그러실까요??
현재 onBindViewHolder안  holder apply 안에 binding.executePendingBindings() 가 적용되어 있습니다~!

2022-02-17 08:53 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/viewmodel/MainViewModel.kt
>      val behaviorSubject = BehaviorSubject.createDefault(0L)
음  요거는  현재  뒤로가기 용으로  적용되어있습니다~!
mainviewmodel backPressCheck() 를  확인해주세요~!

2022-02-17 08:56 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/res/layout/activity_main.xml
> +    </data>
[a25cefa](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/17/commits/a25cefa685270f034b43454e7e2c7f68719ff879)  <data> 태그  제거하였습니다~!

2022-02-17 09:26 UTC, DavidKwon7 approved these changes
확인했습니다~ 고생하셨습니다!

2022-02-17 09:26 UTC, DavidKwon7 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/viewmodel/MainViewModel.kt
>      val behaviorSubject = BehaviorSubject.createDefault(0L)
아.. 제가 전체 코드를 못 봐서 착각한 것 같네요 
네넵 알겠습니다!

2022-02-17 09:26 UTC, DavidKwon7 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/adapter/UserListRvAdapter.kt
> +            binding.executePendingBindings()
그러네요 제가 윗 부분을 펼쳐보지 않아서 오해했네요~

2022-02-18 03:50 UTC, sageHabitus requested changes

2022-02-18 03:50 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/util/BindingAdapter.kt
> +        (adapter as ListAdapter<T, VH>).submitList(null)
adapter nullable check 해주세요

2022-02-18 03:50 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/util/BindingAdapter.kt
> +        (adapter as ListAdapter<T, VH>).submitList(null)
이건 굳이 나눌 필요 있을까요??

2022-02-18 03:50 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/util/BindingAdapter.kt
> +    }
한줄로 줄일 수 있습니다

2022-02-18 03:50 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/viewmodel/DetailViewModel.kt
> +    private var _repoDetailList = MutableLiveData<List<PresentationUserRepo>>()
var -> val

2022-02-18 03:50 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/viewmodel/DetailViewModel.kt
>                  val presentationUserRepoList = dataModelUserRepoList.map { toPresentationModel(it) }
요걸 위의 observable의 map operator 로 넣고 그 결과만 subscribe해서 바로 받을 수 있을 것 같습니다.

2022-02-18 03:50 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/viewmodel/MainViewModel.kt
> +    var vmFavoriteUserList: MutableList<PresentationSearchedUser>? = mutableListOf()
var -> val

2022-02-18 03:50 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/viewmodel/SplashViewModel.kt
> +                _searchedUserList.value = searchedUsersList?.let {
요것도 스트림 형태의 operator로 분리해주세요

2022-02-18 03:50 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/res/layout/activity_detail.xml
> +            name="thisFragment"
변수명이 왜 이런가요?

2022-02-18 03:50 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/res/layout/activity_detail.xml
> +            android:id="@+id/rcy_user_repo_list"
id 관련 rcy 지우주시고 rv로 바꿔주세요

2022-02-18 03:50 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/res/layout/activity_splash.xml
> +            android:id="@+id/imageView"
변수명 컨벤션

2022-02-18 03:50 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/res/layout/fragment_favorite.xml
> +            name="mainViewModel"
변수명

2022-02-18 03:50 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/res/layout/fragment_user.xml
> +            android:id="@+id/edit_search_user"
et_blah 로 바꿔주세요

2022-02-18 03:50 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/res/layout/fragment_user.xml
> +            android:id="@+id/rcy_user_list"
rcy -> rv

2022-02-18 03:50 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/res/layout/item_repo_user.xml
> +            android:id="@+id/img_user_profile"
img -> iv

2022-02-18 03:50 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/res/layout/item_repo_user.xml
> +            android:id="@+id/img_btn_favorite"
img -> iv

2022-02-18 18:18 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/util/BindingAdapter.kt
> +        (adapter as ListAdapter<T, VH>).submitList(null)
[7fb4e75](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/17/commits/7fb4e75e1dff28d6f4e99e5e010b665ee5bbf8bf)[](https://github.com/realizer12) 

 수정했는데,  밑에 이슈 처리하면서  사라졌네요 ㅎㅎ;;
근데 nullable check가 요 커밋에  적용한대로 하라는 말씀이 맞을까요??

2022-02-18 18:19 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/util/BindingAdapter.kt
> +        (adapter as ListAdapter<T, VH>).submitList(null)
[43f1aa4](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/17/commits/43f1aa4be817a118f5964d31faa2b72b360e5a7b)
empty일때  초기화 하려고 했었는데 ,
생각 해보니  empty상태이면  새로 업데이트 될것 같습니다 ㅎㅎ 

수정하였습니다!

2022-02-18 18:20 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/util/BindingAdapter.kt
> +    }
[374849e](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/17/commits/374849e2feec356f05d1df67a116a2f66fc9379a) 수정 커밋입니다~!

2022-02-18 18:20 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/viewmodel/DetailViewModel.kt
> +    private var _repoDetailList = MutableLiveData<List<PresentationUserRepo>>()
[8d5b28b](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/17/commits/8d5b28b19de8dcc75affbc631d5d02d23e924555) 수정 커밋입니다!

2022-02-18 18:20 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/viewmodel/DetailViewModel.kt
> +    private var _error = MutableLiveData<Throwable>()
[8d5b28b](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/17/commits/8d5b28b19de8dcc75affbc631d5d02d23e924555) 수정 커밋입니다~!

2022-02-18 18:21 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/viewmodel/DetailViewModel.kt
> +    //레포리스트 라이브데이터
[d2828f1](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/17/commits/d2828f1c5fbb4e0aea723773a865a62a4b5623c3) 수정 커밋입니다~!

2022-02-18 18:21 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/viewmodel/MainViewModel.kt
> +    var vmFavoriteUserList: MutableList<PresentationSearchedUser>? = mutableListOf()
[c168d2b](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/17/commits/c168d2bc2f9c1f06820429dfe2be05e55fb634ef) 수정 커밋입니다~!

2022-02-18 18:22 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/viewmodel/MainViewModel.kt
> +    val searchedUsersList: LiveData<List<PresentationSearchedUser>> = _searchedUserList
[8d5b28b](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/17/commits/8d5b28b19de8dcc75affbc631d5d02d23e924555) 수정 커밋입니다~!

2022-02-18 18:22 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/viewmodel/SplashViewModel.kt
> +                _searchedUserList.value = searchedUsersList?.let {
[599b049](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/17/commits/599b049949a342f25aa35a85b5917b5e851efb78) 수정 커밋입니다~!

2022-02-18 18:22 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/res/layout/activity_detail.xml
> +            name="thisFragment"
[b91a81a](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/17/commits/b91a81abd2c80afa736c3d96768e6ac3a5f2d6ac) 수정 커밋입니다~!

2022-02-18 18:23 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/res/layout/activity_detail.xml
> +            android:id="@+id/rcy_user_repo_list"
[8b4b21b](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/17/commits/8b4b21b1987798abf19c54bfce94436f34bedd36) 수정 커밋입니다~!

2022-02-18 18:25 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/res/layout/fragment_favorite.xml
> +            name="mainViewModel"
[4cf94de](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/17/commits/4cf94de7161da2608175b24f8efaff3f7b7782f9)
 수정 커밋입니다~! 
mainVm 이라고 바꿨는데  맞는지 모르겠습니다 ㅎㅎ;;
main을  쓴 이유는  fragment에서  shared view model 외의   다른 뷰모델을 가질수 있다고 생각해서  구분을 위해 넣었는데  혹시 빼야될까요??

2022-02-18 18:25 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/res/layout/fragment_user.xml
> +            android:id="@+id/rcy_user_list"
[23b7e98](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/17/commits/23b7e98945bcbb3c6335255b522d52c0103e1832) 수정 커밋입니다~!

2022-02-18 18:25 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/res/layout/item_repo_user.xml
> +            android:id="@+id/img_user_profile"
[df151dd](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/17/commits/df151ddfed1aee8c23480ddb9584d036c27d212d) 수정 커밋입니다~!

2022-02-18 18:26 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/res/layout/item_repo_user.xml
> +            android:id="@+id/img_btn_favorite"
[df151dd](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/17/commits/df151ddfed1aee8c23480ddb9584d036c27d212d) 수정 커밋입니다~!

2022-02-19 02:34 UTC, sageHabitus approved these changes

2022-02-19 02:35 UTC, sageHabitus commented
고생하셨습니다!

2022-02-19 02:35 UTC, merged