3주차 과제 다시 제출합니다~
AndroidTutoring/Android_CleanArchitecture_Tutoring pull request #19
Opened 2022-02-16 12:02 UTC by DavidKwon7

3주차 과제 다시 제출합니다~

2022-02-16 16:09 UTC, realizer12 requested changes

2022-02-16 16:09 UTC, realizer12 commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/MainActivity.kt
> +            adapter.addItem(it)
음 이부분은 바인딩 어뎁터로 처리하고 있는것 같습니다!
지워도 될것 같은데 확인해주세요!

2022-02-16 16:09 UTC, realizer12 commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/MainViewModel.kt
> +    var progressBarVisible: MutableLiveData<Boolean> = MutableLiveData()
음 activity_main xml 상에서는   bind:setProgressBar  로 바인딩이 되어있는 값  같은데  
따로 값 변환이 안되고 있는것 같습니다!
확인해주세요~!

2022-02-16 16:09 UTC, realizer12 commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/ProfileAdapter.kt
> +        fun bind(item: UserDataModel) {
음 요부분  UserPresentationDataModel로  바뀌어야될것 같아요~!
뷰모델에에서 datamodule로부터 받아온 UserDataModel을   UserPresentationDataModel로 매핑 한 후 부터는,  
뷰 쪽에서는  UserPresentationDataModel 모델을  사용해야 할것 같습니다~!

2022-02-17 05:26 UTC, DavidKwon7 commented on 20220122_DavidKwon7/presentation/build.gradle
> +        dataBinding true
aa7aced730a1e4ffd6b1a37a3ef2fdd43de77671
app module에 data binding 추가

2022-02-17 06:38 UTC, DavidKwon7 commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/FavoriteViewModel.kt
> +    val publishSubject : PublishSubject<List<UserDataModel>> =
6e56b214ffe2c4937433fa0a8fc6179030a54456
publishSubject 제거

2022-02-17 06:38 UTC, DavidKwon7 commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/UserPresentationDataModel.kt
> +            return user.toList().map {
a4f51c6996690fb1dc90e24da03fe54f9b7eeef8
mapping 수정!

2022-02-17 06:38 UTC, DavidKwon7 commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/MainActivity.kt
> +            adapter.addItem(it)
a76e5c026488665bc8d4b17d595dffada66814fd
adapter.addItem 제거 

네넵, 중복으로 기능을 넣었네요

2022-02-17 06:38 UTC, DavidKwon7 commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/ProfileAdapter.kt
> +        fun bind(item: UserDataModel) {
958aa03e7af3f907ead5e3ca4eb44d9aec81ca64
Model : Data -> Presentaion 으로 변경 

*언급한 부분 이외에도 동일한 문제점들이 있어서 다 같이 수정하였습니다 :)

2022-02-17 10:53 UTC, DavidKwon7 reviewed
peer review 수정

2022-02-17 10:53 UTC, DavidKwon7 commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/MainViewModel.kt
> +    var progressBarVisible: MutableLiveData<Boolean> = MutableLiveData()
e8b1c6570c81cadce3bc7852355f3ff126fcf0df
data binding 관련 progressBar 수정!!

2022-02-17 11:12 UTC, realizer12 approved these changes
저는 리뷰 끝났습니다~!   수고하셨습니다!

2022-02-18 03:34 UTC, sageHabitus requested changes

2022-02-18 03:34 UTC, sageHabitus commented on 20220122_DavidKwon7/data/src/main/java/com/example/data/Room/UserDao.kt
> +    @Query("SELECT * FROM userdatamodel")
테이블 이름에서 datamodel은 빼주세요

2022-02-18 03:34 UTC, sageHabitus commented on 20220122_DavidKwon7/data/src/main/java/com/example/data/Retrofit/RetrofitClient.kt
> +    private val InstanceBuilder by lazy {
instanceBuilder 대신에 다른 이름으로 해주세요

2022-02-18 03:34 UTC, sageHabitus commented on 20220122_DavidKwon7/data/src/main/java/com/example/data/model/UserDataModel.kt
> +                         val url: String?)
) 은 줄바꿈 해주세요

2022-02-18 03:34 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/BindingAdapters.kt
> +    @BindingAdapter("bind:setProgressBar")
setProgressBar보다는 loading이나 visible관련 네이밍이 좋을 것 같습니다

2022-02-18 03:34 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/BindingAdapters.kt
> +        view.visibility=if (isVisible)View.VISIBLE else View.GONE
리포맷

2022-02-18 03:34 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/BindingAdapters.kt
> +        (adapter as ProfileAdapter).addItem(list)
nullable체크 해주세요

2022-02-18 03:34 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/BindingAdapters.kt
> +    @BindingAdapter("addList")
이건 bind:가 없네요

2022-02-18 03:34 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/FavoriteActivity.kt
> +    private val listData = listOf<UserDataModel>()
userDataModelList라고 명확히 하는게 좋습니다

2022-02-18 03:34 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/FavoriteActivity.kt
> +        favoriteViewModel.list.observe(this, Observer { it->
it은 생략 가능합니다

2022-02-18 03:34 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/FavoriteActivity.kt
>                      date = String(),
이 코드는 뭔가요??

2022-02-18 03:34 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/FavoriteAdapter.kt
> +        val listItemBinding = ItemRecyclerExBinding.inflate(inflater,parent,false)
ItemRecyclerEx 너무 네이밍이 추상적이고 모호합니다

2022-02-18 03:34 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/FavoriteViewModel.kt
> +    private val githubRepos: ArrayList<UserDataModel> = ArrayList()
mutableList로 바꿔주세요

2022-02-18 03:34 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/MainActivity.kt
>                      name=String(),id= String(),date = String(),url = String() ))
해당 코드는 다시 생각해보세용

2022-02-18 03:34 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/MainActivity.kt
> +            override fun onItemClick(v: View, data: UserDataModel, pos: Int) {
줄바꿈 규칙이 통일돼야 할 것 같네요

2022-02-18 03:34 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/MainActivity.kt
>      private fun back2() {
back2 네이밍이 너무 이상합니다. 숫자는 지양해주세요

2022-02-18 03:34 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/ProfileDetailActivity.kt
> +        val url :TextView = binding.htmlUrl
이렇게 재할당할 필요없을 것 같습니다

2022-02-18 03:34 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/UserPresentationDataModel.kt
> +        }
이거 말씀드린 것 같은데 List말고 Model하나를 받아주시고 map을 밖에서 해주세요

2022-02-18 03:34 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/UserPresentationDataModel.kt
> +
이거 말씀드린 것 같은데 List말고 Model하나를 받아주시고 map을 밖에서 해주세요

2022-02-18 03:34 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/res/layout/activity_favorite.xml
> +            android:id="@+id/btn1"
네이밍 수정

2022-02-18 03:34 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/res/layout/activity_favorite.xml
> +            android:id="@+id/btn2"
네이밍 수정

2022-02-18 03:34 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/res/layout/activity_main.xml
> +            name="mainVM"
vm또는 viewModel로 바꿔주세요

2022-02-18 03:34 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/res/layout/activity_main.xml
> +            type="java.lang.Boolean" />
컴포넌트 이름이 변수명은 좀 이상합니다

2022-02-18 03:34 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/res/layout/item_recycler_fav.xml
> +            android:text="@{User.url}"
variable 네이밍 컨벤션 지켜주세요

2022-02-18 23:53 UTC, DavidKwon7 commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/FavoriteActivity.kt
>                      date = String(),
2078adc781fef3f9c6390ab1d4e96a105639c434
favorite delete 관련 수정

2022-02-18 23:54 UTC, DavidKwon7 commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/MainActivity.kt
>                      name=String(),id= String(),date = String(),url = String() ))
5ca73326dc108cea2b2fac90240cfad4221fff61
favorite click 관련 코드 수정

2022-02-19 02:51 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/MainViewModel.kt
> +    var progressBarVisible: MutableLiveData<Boolean> = MutableLiveData()
var -> val

2022-02-19 02:52 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/MainViewModel.kt
> +    private var api= GithubAPI::class.java
var -> val, 이렇게 선언할 이유가 있나요?

2022-02-19 02:53 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/MainViewModel.kt
> +    val list : LiveData<List<UserDataModel>> = _list
변수명이 애매합니다

2022-02-19 02:53 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/MainViewModel.kt
> +    fun saveData(data:UserDataModel){
리포맷 잘 안하시는 느낌이 드네요 항상 제대로 해주세요

2022-02-19 02:53 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/MainViewModel.kt
> +            .subscribe({it->
it

2022-02-19 02:53 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/MainViewModel.kt
>          compositeDisposable.add(githubRepository.getRepos()
addTo extension으로 빼주세요

2022-02-19 02:54 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/res/layout/activity_profile_detail.xml
> +            android:id="@+id/fav_btn"
네이밍 컨벤션

2022-02-19 02:55 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/res/layout/item_recycler_fav.xml
> +            android:id="@+id/created_time"
네이밍 컨벤션

2022-02-19 02:55 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/res/layout/item_recycler_fav.xml
> +            android:text="@{User.date}"
user가 왜 파스칼일까요?

2022-02-19 02:55 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/res/layout/item_recycler_fav.xml
> +            android:id="@+id/html_url"
컨벤션

2022-02-19 02:58 UTC, sageHabitus commented
fyi) 네이밍컨벤션 관련 자료 
https://medium.com/mindorks/android-resource-naming-convention-42e4e8026614#:~:text=Layout%20files%20should%20match%20the,xml.

그리고 중복된 코멘트가 있을 수 있으니 보고 넘어가주세요~

2022-02-19 14:01 UTC, DavidKwon7 reviewed
제출합니다!

2022-02-19 14:45 UTC, sageHabitus requested changes

2022-02-19 14:45 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/res/layout/item_recycler_fav.xml
> +            android:text="@{User.url}"
User를 바꿔달라는 말이었어요 대문자면 안되니까요

2022-02-19 14:45 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/res/layout/item_recycler_fav.xml
> +            android:text="@{User.url}"
그리고 user_ 식의 네이밍을 뷰_ 식으로 바꿔주세요

2022-02-19 14:45 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/res/layout/item_recycler_fav.xml
> +            android:text="@{User.url}"
전체적으로 정확히 다시 봐주세요

2022-02-19 14:46 UTC, sageHabitus commented on 20220122_DavidKwon7/data/src/main/java/com/example/data/Retrofit/RetrofitClient.kt
> +    val createGithubAPI : GithubAPI by lazy {
githubApi라고 말씀드렸는데 lazy를 제거하신 이유가 뭔가요?

2022-02-20 02:51 UTC, DavidKwon7 reviewed
다시 제출합니다!!!

2022-02-20 02:51 UTC, DavidKwon7 commented on 20220122_DavidKwon7/data/src/main/java/com/example/data/Retrofit/RetrofitClient.kt
> +    val createGithubAPI : GithubAPI by lazy {
8aead71f1edfcc21b7c928fd8e52523a839f8806
제가 말씀하신 걸 잘못 이해한 것 같네요 !
val createGithubAPI -> val githubAPI 으로 변경해주었습니다. 

성재님! 코드 수정하면서 의문이 생겼는데, by lazy 를 사용하면 호출되었을 때 초기화를 하잖아요. 때문에 by lazy 사용 유무에 따라 효율성에 대해 차이가 발생하기 때문에 by lazy를 사용하는 건가요? ( + 안정적인 null 처리)

2022-02-20 02:51 UTC, DavidKwon7 commented on 20220122_DavidKwon7/presentation/src/main/res/layout/item_recycler_fav.xml
> +            android:text="@{User.url}"
416e3a79464b1d7987f697fa920b5773d3104756
layout에 naming convention 적용하여 전체 변경!

2022-02-20 08:31 UTC, sageHabitus approved these changes

2022-02-20 08:31 UTC, merged