4주차 과제 pr 입니다~!
AndroidTutoring/Android_CleanArchitecture_Tutoring pull request #22
Opened 2022-02-23 18:47 UTC by realizer12

4주차 과제  pr입니다~!

1. data 모듈 -> local, remote module 한번더 분기
2. retrofit,room, datasource, repository ,viewmodel에  hilt 적용

2022-02-24 08:08 UTC, DavidKwon7 requested changes
리뷰입니다

2022-02-24 15:52 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/fragment/FavoriteFragment.kt
> +@AndroidEntryPoint
[d2e2a01](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/22/commits/d2e2a010870794865ec756075d23cbf1ebf528c9)  수정 커밋입니다~!

2022-02-24 15:52 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/fragment/UserFragment.kt
> +@AndroidEntryPoint
[d2e2a01](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/22/commits/d2e2a010870794865ec756075d23cbf1ebf528c9) 수정 커밋입니다~

2022-02-25 01:29 UTC, DavidKwon7 approved these changes
확인 하였습니다!

2022-02-25 05:51 UTC, sageHabitus requested changes

2022-02-25 05:51 UTC, sageHabitus commented on 20220122_realizer12/local/src/main/java/com/example/local/di/LocalModule.kt
> +    }
thread safe 하게 바꿔야 되지 않을까요?

2022-02-25 05:51 UTC, sageHabitus commented on 20220122_realizer12/local/src/main/java/com/example/local/di/LocalModule.kt
> +    }
delete return

2022-02-25 05:51 UTC, sageHabitus commented on 20220122_realizer12/local/src/main/java/com/example/local/impl/UserLocalDataSourceImpl.kt
> +    }
delete return

2022-02-25 05:51 UTC, sageHabitus commented on 20220122_realizer12/local/src/main/java/com/example/local/impl/UserLocalDataSourceImpl.kt
> +    override fun deleteFavoriteUser(deletedFavoriteUser: SearchedUser): Completable {
data layer model은 뒤에 DataModel을 붙여주세요

2022-02-25 05:51 UTC, sageHabitus commented on 20220122_realizer12/local/src/main/java/com/example/local/model/SearchedUserLocal.kt
> +    @ColumnInfo(name = "is_my_favorite") var isMyFavorite: Boolean = false//유저 repo url
오른쪽 주석은 지워주셔도 되고 위의 전체적으로 적는게 좋을 것 같습니다 /**

2022-02-25 05:51 UTC, sageHabitus commented on 20220122_realizer12/local/src/main/java/com/example/local/model/SearchedUserLocal.kt
> +            )
return 지워주시고 DataModel, Room은 RoomObject or RoomModel로 변경해주세요. 확장함수로 중복코드 지워주세요~(with,run)

2022-02-25 05:51 UTC, sageHabitus commented on 20220122_realizer12/local/src/main/java/com/example/local/room/FavoriteDao.kt
> +    fun getFavoriteGitUsers(isMyFavorite: Boolean): Single<List<SearchedUserLocal>>
DTO naming, annotation delete

2022-02-25 05:51 UTC, sageHabitus commented on 20220122_realizer12/local/src/main/java/com/example/local/room/LocalDataBase.kt
> +    exportSchema = false//schema 구조 export false처리
annotation delete

2022-02-25 05:51 UTC, sageHabitus commented on 20220122_realizer12/local/src/main/java/com/example/local/room/LocalDataBase.kt
> +    abstract fun getFavoriteMarkDao(): FavoriteDao
get말고 그냥 favoriteDao로 해주세요

2022-02-25 05:51 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/activity/DetailActivity.kt
>      private var userInfo: PresentationSearchedUser? = null
Presentation DTO 는 뒤에 PresentationModel을 붙이거나 이게 아니라면 PresentationModel을 제외한 다른 레이어들은 layer 에 맞게 naming 다시 해주세요. responseModel, requestModel 등등

2022-02-25 05:51 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/activity/MainActivity.kt
> +    @Inject lateinit var userRepository: UserRepository
annotation은 항상 줄바꿈 해주세요 그리고 Repository는 이제 뷰가 알면 안됩니다

2022-02-25 05:51 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/activity/SplashActivity.kt
> +    @Inject lateinit var userRepository: UserRepository
위 코멘트와 동일

2022-02-25 05:51 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/base/BaseFragment.kt
>  open class BaseFragment<VDB: ViewDataBinding>(@LayoutRes val layRes:Int): Fragment() {
리포맷 안돼있네요

2022-02-25 05:51 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/fragment/FavoriteFragment.kt
>          binding.rcyFavoriteList.apply {
바꾸신다고 하셨는데 안바꿔주셨네요

2022-02-25 05:51 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/viewmodel/DetailViewModel.kt
>      private val repoRepository: RepoRepository
RepoRepository보다는 좀 더 명확한 변수명이 좋을 것 같습니다. Repo라는게 여러 도메인이 있을 수 있습니다. 이것도 코멘트 드린 것 같아요. 또한 관련 변수명도 다 수정이 필요할 것 같아요

2022-02-25 05:51 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/viewmodel/MainViewModel.kt
>                                  dataModelSearchUserList.map { toPresentationModel(searchedUser = it) }
특정클래스에 맞춰서 확장함수 형태로 구현된게 아니고, 줄여서 하게 되는 경우 Mapper가 많아지면 가독성이 매우 떨어질 것 같은데 어떻게 생각하시나요? (모든 Mapper에 Companion 생략한거에 대한 말씀을 드립니다) 이렇게 구현하길 원하신다면 companion이 아니라 확장함수로 빼시는걸 추천드립니다.

2022-02-25 05:51 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/viewmodel/MainViewModel.kt
> +                //}
이런 필요없는 주석은 지워주세요~

2022-02-25 05:51 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/viewmodel/MainViewModel.kt
>                      return@zip vmSearchedUsersList.map { it.copy() }//깊은 복사 안하면 계속 adapter의 리스트와 동기화되어서  사용함.
이거 정말 해결 안될까요??

2022-02-25 05:51 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/viewmodel/MainViewModel.kt
> +                _favoriteUserList.value = vmFavoriteUserList
변수명에서 List에서 vm은 지워주세요

2022-02-25 05:51 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/viewmodel/SplashViewModel.kt
>              userRepository.getSearchUsers(query = "realizer12", 1, 10)
이런것도 초기값 default로 빼주시는게 좋습니다.

2022-02-25 05:51 UTC, sageHabitus commented on 20220122_realizer12/remote/src/main/java/com/example/remote/di/RemoteModule.kt
> +    }
reformat, delete return

2022-02-25 05:51 UTC, sageHabitus commented on 20220122_realizer12/remote/src/main/java/com/example/remote/di/RemoteModule.kt
> +            .baseUrl(ServerIp.BaseUrl)
BASEURL에 따라 Retorift 객체가 많아질 경우를 대비해서 분리해주세요

2022-02-25 05:51 UTC, sageHabitus commented on 20220122_realizer12/remote/src/main/java/com/example/remote/di/RemoteModule.kt
> +        apiService: ApiService
무슨 API인지 명시해주세요

2022-02-25 05:51 UTC, sageHabitus commented on 20220122_realizer12/remote/src/main/java/com/example/remote/impl/UserRemoteDataSourceImpl.kt
> +class UserRemoteDataSourceImpl @Inject constructor(private val apiService: ApiService) :
이건 왜 줄바꿈을 안하신걸까요?

2022-02-25 05:51 UTC, sageHabitus commented on 20220122_realizer12/remote/src/main/java/com/example/remote/impl/UserRemoteDataSourceImpl.kt
> +        return apiService.searchUsers(query, page, perPage).map {
delete return, chaining line

2022-02-25 05:51 UTC, sageHabitus commented on 20220122_realizer12/remote/src/main/java/com/example/remote/model/SearchedUserRemote.kt
> +            return SearchedUser(
return, scope function

2022-02-25 05:51 UTC, sageHabitus commented on 20220122_realizer12/remote/src/main/java/com/example/remote/model/SearchedUserRemote.kt
> +    var isMyFavorite: Boolean = false//유저 repo url
clear annotation

2022-02-25 05:51 UTC, sageHabitus commented on 20220122_realizer12/remote/src/main/java/com/example/remote/model/SearchedUserRemote.kt
> +data class SearchedUserRemote(
change suffix ResponseModel or RequestModel

2022-02-25 05:51 UTC, sageHabitus commented on 20220122_realizer12/remote/src/main/java/com/example/remote/model/SearchedUserRemote.kt
> +        //데이터 모듈 데이터 모델로
annotation

2022-02-25 05:51 UTC, sageHabitus commented on 20220122_realizer12/remote/src/main/java/com/example/remote/model/SearchedUsersRemote.kt
> +    var items: ArrayList<SearchedUserRemote>? = null,//검색된 유저 리스트
var -> val

2022-02-25 05:51 UTC, sageHabitus commented on 20220122_realizer12/remote/src/main/java/com/example/remote/model/SearchedUsersRemote.kt
> +                    SearchedUserRemote.toDataModel(
chaining

2022-02-25 05:51 UTC, sageHabitus commented on 20220122_realizer12/remote/src/main/java/com/example/remote/model/SearchedUsersRemote.kt
> +    var total_count: Int? = null//전체 카운트
annotation must have space

2022-02-25 05:51 UTC, sageHabitus commented on 20220122_realizer12/remote/src/main/java/com/example/remote/model/UserRepoRemote.kt
> +    var stargazers_count: Int? = null
don't use under_bar

2022-02-25 05:51 UTC, sageHabitus commented on 20220122_realizer12/remote/src/main/java/com/example/remote/model/UserRepoRemote.kt
> +            return UserRepo(
refer above comments please

2022-02-25 13:42 UTC, sageHabitus requested changes

2022-02-25 13:42 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/viewmodel/MainViewModel.kt
> +                 //   throw RuntimeException()
```suggestion
                     fun searchUser(searchQuery: String, page: Int, perPage: Int) {
        //local , remote  zip으로  동시에 다 처리되면  뿌려지게 수정
        Single.zip(
            userRepository
                .getSearchUsers(
                    searchQuery,
                    page,
                    perPage
                ).subscribeOn(Schedulers.io())
                .retry(2),
            userRepository
                .getFavoriteUsers()
        ) { remote, local ->

            if (page == 1) {
                vmSearchedUsersList.clear()
            }
            return@zip remote.items.let { dataModelSearchUserList ->
                if (!dataModelSearchUserList.isNullOrEmpty()) {
                    val presentationSearchUserList = dataModelSearchUserList
                        .map { toPresentationModel(searchedUser = it) }

                    vmSearchedUsersList.addAll(presentationSearchUserList)
                }
                vmSearchedUsersList.map { searchedUser ->
                    searchedUser.copy(isMyFavorite = local.any { it.id == searchedUser.id })
                }
            }
        }
            .observeOn(AndroidSchedulers.mainThread())
            .subscribe({ searchedUsersList ->
                _searchedUserList.value = searchedUsersList
            }, {
                _error.value = Throwable("유저를 검색하는 중에문제가 생감")
            })
            .addTo(compositeDisposable)
    }
```

2022-02-25 13:43 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/viewmodel/MainViewModel.kt
> +                 //   throw RuntimeException()
diffUtil이 안먹힌 이유는 복사 문제가 아닙니다~!

2022-03-13 16:44 UTC, closed without merging