4주차 과제 제출합니다!!!
AndroidTutoring/Android_CleanArchitecture_Tutoring pull request #23
Opened 2022-02-24 05:15 UTC by DavidKwon7

github에 올리지 않아도 되는 파일이 올라가는 이유가 .gitignore를 제대로 사용하지 않아서라는 것을 파악하고 .gitignore를 제대로 적용해 주었습니다. 
이미 올라가져 있는 파일들을 수정하기 위해 저번주 upstream에 merge된 부분부터 다시 작업을 했습니다. (이 과정을 통해 필요 없는 파일을 많이 지울 수 있었지만, 그 이전부터 존재했던 파일들을 지우지는 못 했네요..)

위의 작업을 수행하면서 좀 더 commit을 세세하게 구성하려고 노력했습니다. 

저번주 과제에서 누락된 부분들이 있어서 수정을 해주었습니다! 

* 처음부터 다시 작성한 코드여서 누락된 부분이 있을 수도 있는데, 알려주시면 빠르게 수정하겠습니다! 😄

2022-02-24 15:49 UTC, realizer12 requested changes

2022-02-24 15:49 UTC, realizer12 commented on 20220122_DavidKwon7/presentation/build.gradle
> +    implementation "com.google.dagger:hilt-android:2.35"
음 아래 kapt랑  version이 다른데 혹시  빌드 잘되셨나요??
그리고 현재  hilt version이  제가 확인한 바로는 2.41 버전까지  나온것 같습니다.~!
공식 문서에서는  영어로 봤을때 2.38.1로  사용하고 있네요..
(https://developer.android.com/training/dependency-injection/hilt-android)

한국어로  보면 2.28-alph를 사용하고 있는데  아직  문서 업데이트를  안해준거 같아요;;

2022-02-24 15:49 UTC, realizer12 commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/di/module/RepositoryModule.kt
> +    abstract fun provideLocalDataSource(localDataSource: LocalDataSource) : LocalDataSource
음 이렇게 binds를 사용할때는  매개변수에  inteface의  구현체를 넘겨줘야될것 같습니다~!
현재는  interface를  매개변수로  넘겨주는것 같습니다~!
확인 해주세요!

https://developer.android.com/training/dependency-injection/hilt-android?hl=ko

![image](https://user-images.githubusercontent.com/59385193/155556084-9387ee69-a1af-4baf-9d63-1a19ef081d71.png)

2022-02-24 15:49 UTC, realizer12 commented on 20220122_DavidKwon7/localData/src/main/java/com/example/localdata/source/LocalDataSourceImpl.kt
> +) : LocalDataSource {
음 impl은   local  모듈로 옮겨졌으니 ,  addFav나  , deletefav들  local data class로 변환되어  넣어주어야 할것 같아요~
확인해주세요!

2022-02-25 03:49 UTC, DavidKwon7 reviewed
수정하였습니다~

2022-02-25 03:49 UTC, DavidKwon7 commented on 20220122_DavidKwon7/localData/src/main/java/com/example/localdata/source/LocalDataSourceImpl.kt
> +) : LocalDataSource {
b766f85bb5fa383963d775d1ae3bcba50e08a5b8
add, delete 관련 수정!

2022-02-25 03:49 UTC, DavidKwon7 commented on 20220122_DavidKwon7/data/src/main/java/com/example/data/model/UserDataModel.kt
> +@Entity(tableName = "user")
c9a9142b0b011959400b25028aa02a8c88544020

저도 찾아보았는데, 동훈님 말씀이 맞는 것 같아 @Entity 수정하였습니다. 
(room 관련해서는 local에서 처리해주어야 하니까 local data class에 @Entity 를 달아주는게 맞는 것 같아요! )

2022-02-25 03:49 UTC, DavidKwon7 commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/di/module/RepositoryModule.kt
> +    abstract fun provideLocalDataSource(localDataSource: LocalDataSource) : LocalDataSource
b95aecc295b97edb7cfc27b2dc7ef96af64260c5

앗..! impl 을 안 달았네요
알려주셔서 감사합니다

2022-02-25 08:59 UTC, realizer12 approved these changes

2022-02-25 08:59 UTC, realizer12 commented
수고하셨습니다~!

2022-02-25 09:22 UTC, sageHabitus requested changes

2022-02-25 09:22 UTC, sageHabitus commented on 20220122_DavidKwon7/localData/src/main/java/com/example/localdata/room/UserDao.kt
> +                >) : Completable
어차피 local이기 때문에 local 관련 변수명은 제거해도 되지 않을까요? + 줄바꿈이 아쉽네요
pair를 쓰는 이유가 있을까요?

2022-02-25 09:22 UTC, sageHabitus commented on 20220122_DavidKwon7/localData/src/main/java/com/example/localdata/room/UserDao.kt
> +                >) : Completable
줄바꿈이 아쉽습니다

2022-02-25 09:22 UTC, sageHabitus commented on 20220122_DavidKwon7/localData/src/main/java/com/example/localdata/source/LocalDataSourceImpl.kt
> +    private val userMapper: LocalToUserMapper<UserLocalDataModel, UserDataModel>
Mapper를 주입 받는 이유가 있을까요?

2022-02-25 09:22 UTC, sageHabitus commented on 20220122_DavidKwon7/localData/src/main/java/com/example/localdata/source/LocalDataSourceImpl.kt
> +        return dao.deleteFav(user = userLocalDataModel)
delete return statement

2022-02-25 09:22 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/build.gradle
> +    kapt "com.google.dagger:hilt-android-compiler:2.38.1"
굳이 2.38.1로 하는 이유가 있을까요?

2022-02-25 09:22 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/FavoriteActivity.kt
> +            })
Livedata 관련 확장함수로 바꿔보는게 어떨까요 + Observer 명시는 필요할까요??

2022-02-25 09:22 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/FavoriteAdapter.kt
>      var postList = listOf<UserDataModel>()
var to val

2022-02-25 09:22 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/MainActivity.kt
>      private val githubRepos: ArrayList<UserDataModel> = ArrayList()
to MutableList

2022-02-25 09:22 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/MainActivity.kt
> +    private lateinit var githubAPI: GithubAPI
?? 이게 뭘까요

2022-02-25 09:22 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/MainActivity.kt
> +            startActivity(Intent(this, FavoriteActivity::class.java))
확장함수를 써서 더 간단하게 고쳐보시겠어요?

2022-02-25 09:22 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/MainActivity.kt
> +        binding.goToFavorite.setOnClickListener {
해당 버튼 이벤트도 databinding으로 뺄 수 있을 것 같습니다

2022-02-25 09:22 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/MainActivity.kt
> +                        name = "",
delete 할 때, 객체가 아니라 해당 id만 넘기게끔 고쳐주세요

2022-02-25 09:22 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/MainActivity.kt
> +            adapter = ProfileAdapter(listData, this@MainActivity)
listData 메서드로 빼달라고 말씀드린 것 같습니다

2022-02-25 09:22 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/MainViewModel.kt
>          roomDatabaseInstance?.userDao()?.loadUserList()
nullable to non null

2022-02-25 09:22 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/ProfileAdapter.kt
>          notifyDataSetChanged()
클릭할때마다 notify는 좀 위험해 보입니다.

2022-02-25 09:22 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/ProfileAdapter.kt
>      private val githubRepos: ArrayList<UserDataModel> = ArrayList()
mutablelist

2022-02-25 09:22 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/ProfileAdapter.kt
>  class ProfileAdapter(var postList: List<UserDataModel>, val context: MainActivity) :
don't use constructor

2022-02-25 09:22 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/ProfileAdapter.kt
> +                    ?.context,
이 줄바꿈은 좀 아닌 것 같습니다 + itemView가 왜 nullable 일까요?

2022-02-25 09:22 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/ProfileAdapter.kt
> +                    null
줄바꿈 왜 이렇게 하신걸까요??

2022-02-25 09:22 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/ProfileDetailActivity.kt
> +            ).toString()
????!

2022-02-25 09:22 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/SplashActivity.kt
> +                ).show()
toast 확장함수 만들어주세요

2022-02-25 09:22 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/UserPresentationDataModel.kt
> +            with(user) {
해당부분은 한줄로 만들 수 있는 만큼 만들어주세요

2022-02-25 09:22 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/di/module/LocalDataModule.kt
> +    ).build()
thread-safe하게 만들어주세요

2022-02-25 09:22 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/di/module/RemoteDataModule.kt
> +    }
해당 provider를 한번 더 나눠줄 수 있을 것 같습니다

2022-02-25 09:22 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/di/module/RemoteDataModule.kt
> +            .baseUrl("https://api.github.com/")
private const val 또는 build.gradle 변수로 빼주세요

2022-02-25 09:22 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/java/com/example/presentation/di/module/RemoteDataModule.kt
> +            .baseUrl("https://api.github.com/")
retorift baseurl이 많은 경우엔 어떻게 하실건지 알 수 있을까요?

2022-02-25 09:22 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/res/layout/activity_profile_detail.xml
> +            android:id="@+id/name_tv"
refer above comment

2022-02-25 09:22 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/res/layout/activity_profile_detail.xml
> +            app:layout_constraintTop_toBottomOf="@id/name_tv" />
refer above comment

2022-02-25 09:22 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/res/layout/activity_profile_detail.xml
> +            android:id="@+id/url_tv"
refer above comment

2022-02-25 09:22 UTC, sageHabitus commented on 20220122_DavidKwon7/presentation/src/main/res/layout/activity_profile_detail.xml
> +            app:layout_constraintTop_toBottomOf="@id/created_time_tv"
refer above comment

2022-02-25 09:22 UTC, sageHabitus commented on 20220122_DavidKwon7/remoteData/build.gradle
> +//timber 디버깅 라이브러리 추가
이런거 주의해주세요~

2022-02-25 09:22 UTC, sageHabitus commented on 20220122_DavidKwon7/remoteData/src/main/java/com/example/remotedata/model/UserRemoteDataModel.kt
> +        override fun toUser(userRemoteDataModel: UserRemoteDataModel): UserDataModel =
DTO naming convention 참고해주세요

2022-02-25 09:22 UTC, sageHabitus commented on 20220122_DavidKwon7/remoteData/src/main/java/com/example/remotedata/source/RemoteDataSourceImpl.kt
> +        return githubAPI.getRepos("tkdgusl94")
왜 고정값이 있을까요?

2022-02-25 09:22 UTC, sageHabitus commented on 20220122_DavidKwon7/settings.gradle
> +include ':remoteData'
change naming from localData, remoteData to local, remote

2022-02-25 09:33 UTC, sageHabitus commented on 20220122_DavidKwon7/data/src/main/java/com/example/data/model/UserDataModel.kt
> +@Entity(tableName = "user")
맞습니다 Local data class 즉 RoomObject 자체가 DTO입니다. 거기에 달면 됩니다

2022-04-15 16:02 UTC, merged