1주차 과제  rebase 후  버전입니다!
AndroidTutoring/Android_CleanArchitecture_Tutoring pull request #8
Opened 2022-02-02 11:26 UTC by realizer12

2022-02-02 23:07 UTC, sageHabitus requested changes

2022-02-02 23:07 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/repository/UserRepository.kt
> +interface UserRepository {
nullable 할 필요가 없어보입니다

2022-02-02 23:07 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/repository/UserRepositoryImpl.kt
> +    override fun deleteFavoriteUser(deletedFavoriteUser: SearchedUser):Completable? {
nullable 바꿔주세요.

2022-02-02 23:07 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/source/local/UserLocalDataSource.kt
> +    fun addFavoriteUser(vararg favoriteUser:SearchedUser):Completable?//유저 즐겨찾기에 추가
메서드가 여러 user를 넣는 것인데 vararg로 주셨네요. 하나의 유저 또는 여러 유저를 넣게끔 메서드를 분리해주세요

2022-02-02 23:07 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/room/FavoriteMarkDataBase.kt
> +                        FavoriteMarkDataBase::class.java, "favoriteTable.db"
보통 local db는 하나밖에 존재하지 않고 범용적인 변수명으로 씁니다. 또한 카멜케이스로 쓰지 않습니다.

2022-02-02 23:07 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/room/FavoriteMarkDataBase.kt
> +        fun getInstance(context: Context): FavoriteMarkDataBase? {
non null 하게끔 바꿔주세요. 검색하시면 바로 나옵니다.

2022-02-02 23:07 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/source/local/UserLocalDataSourceImpl.kt
> +class UserLocalDataSourceImpl(private val favoriteDao: FavoriteDao?):UserLocalDataSource {
생산자는 모두 줄바꿈 해주세요

2022-02-02 23:07 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/source/local/UserLocalDataSourceImpl.kt
> +    override fun getFavoriteUsers(): Single<List<SearchedUser>>? = favoriteDao?.getFavoriteGitUsers(true)
nullable을 표현하고 싶으신거면 maybe로 다 바꿔주세요

2022-02-02 23:07 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/source/remote/RepoRemoteDataSource.kt
> +    ): Single<ArrayList<UserRepo>>
arraylist는 쓰지말아주시고 list로 써주세요.

2022-02-02 23:07 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/source/remote/RepoRemoteDataSourceImpl.kt
> +    ): Single<ArrayList<UserRepo>> {
arraylist 쓰지 말아주세요

2022-02-02 23:07 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/source/remote/UserRemoteDataSource.kt
> +        query:String = "",
default값 넣지 말아주세요

2022-02-02 23:07 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/viewholder/UserViewHolder.kt
> +        if (searchedUser.isMyFavorite) {
중복 코드가 많아서 더 줄일 수 있습니다.

2022-02-02 23:07 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/viewholder/UserViewHolder.kt
>      fun bind(searchedUser: SearchedUser){
이런건 한칸 띄어주세요

2022-02-02 23:14 UTC, sageHabitus requested changes

2022-02-02 23:14 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/source/remote/UserRemoteDataSourceImpl.kt
> +       return RetrofitHelper.apiServices.searchUsers(query, page, perPage)
retrofitHelper를 생성자로 받게끔 해주세요

2022-02-02 23:14 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/room/FavoriteMarkDataBase.kt
> +                synchronized(FavoriteMarkDataBase::class) {//중복생성  방지
db는 범용적으로 한개를 쓰기 때문에 범용적인 의미의 변수명으로 해주세요

2022-02-02 23:14 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/room/FavoriteDao.kt
> +    fun getFavoriteGitUsers(isMyFavorite:Boolean): Single<List<SearchedUser>>
parameter 띄어쓰기 해주세요 리포맷이 안된것 같네요

2022-02-02 23:14 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/room/FavoriteDao.kt
> +    fun deleteFavoriteUser(userId:Long?):Completable
nullable 없애주세요

2022-02-02 23:14 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/repository/UserRepositoryImpl.kt
> +    override fun addFavoriteUser(vararg favoriteUser: SearchedUser):Completable? {
return을 명시한것과 안한것의 차이가 뭔가요?? 다 통일 부탁드립니다.

2022-02-02 23:14 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/fragment/UserFragment.kt
> +                    searchedUsersList?.map { searchedUser ->
map에 any를 써버리면 복잡도가 상당히 증가하게 됩니다. 물론 써야하는 경우도 있겠지만 대부분의 경우는 더 간단하게 줄일 수 있습니다. copy를 이용해 간단하게 바꿔주세요

2022-02-02 23:27 UTC, sageHabitus requested changes

2022-02-02 23:27 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/fragment/UserFragment.kt
> +            userRepository.getFavoriteUsers()?.subscribeOn(Schedulers.io())
chaning 줄바꿈 해주세요

2022-02-02 23:27 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/fragment/UserFragment.kt
> +                    userListRcyAdapter.notifyDataSetChanged()//전체 업데이트가 안되어서 이렇게 notify넣어줌.
diffUtil은 notify는 필요하지가 않습니다.

2022-02-02 23:27 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/fragment/UserFragment.kt
> +                        binding.editSearchUser.setText(searchedUsersList!![0].login.toString())
위험한 코드입니다. getOr~~ 메서드로 바꿔주세요

2022-02-02 23:27 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/fragment/UserFragment.kt
> +            searchedUsersList?.map {searchUser->
맵 안에서 하나하나 이렇게 가져와버리면 부하가 상당히 심할 것 같습니다.

2022-02-02 23:27 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/fragment/UserFragment.kt
> +                if(searchedUser.isMyFavorite){
if문 같은 경우에는 보통 길게 빼지않고 앞에서 return 처리로 하는게 명확합니다.

2022-02-02 23:27 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/fragment/UserFragment.kt
> +                        }?.subscribe()
error 처리를 안했기 때문에 error가 난다면 앱이 터집니다.

2022-02-02 23:27 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/fragment/UserFragment.kt
> +                            userListRcyAdapter.notifyItemChanged(position)
notify 필요가 없습니다.

2022-02-02 23:27 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/fragment/UserFragment.kt
> +                        ?.observeOn(AndroidSchedulers.mainThread())
nullable

2022-02-03 13:52 UTC, realizer12 commented on 20220122_realizer12/app/src/main/AndroidManifest.xml
> +        android:name="com.example.presentation.application.GlobalApplication"
[5f43426](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/8/commits/5f434262bfbe9d88279e89153bb4bcfcd899f95c) 수정 커밋입니다!

2022-02-03 14:07 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/activity/DetailActivity.kt
> +                if(!userRepoList.isNullOrEmpty()){
[6b7a871](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/8/commits/6b7a871ab4b2ee6aa2a6b3efab5d7be11d994794)  수정 커밋입니다!

2022-02-03 14:10 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/activity/DetailActivity.kt
>                      repoRcyAdapter.submitList(userRepoList)
[af9b1d7](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/8/commits/af9b1d7d9cb04845f7c6cb7e7ea6f278afde8ec8) 수정 커밋입니다!

2022-02-03 14:21 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/activity/MainActivity.kt
> +        backPressProcess()
[d741cc9](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/8/commits/d741cc91550038951352b747870a6affa97e2a3a)  음 뒤로가기를 체크 한다는 느낌이 강해서  backPressCheck로 바꿔보았는데  어떠신가요??

2022-02-03 14:24 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/activity/MainActivity.kt
> +            .observeOn(AndroidSchedulers.mainThread())
[647cef6](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/8/commits/647cef6c8404c7615b0a222ad9bfb8a56765c848) 수정 커밋입니다~

2022-02-03 14:29 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/activity/SplashActivity.kt
> +    override fun onResume() {
[92800d5](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/8/commits/92800d555fef32810baa624ccb8ad1fa953a60d4)  음   splash에서  통신 문제가 생겨 재시도 후  토스트를 띄었을때, 뒤로가기 버튼으로  backstack에 들어갔다가 다시 실행하는 경우   다시  통신 재시도를  하고 싶어서  onResume에   추가 해보았습니다!    일단  메모리 해제는 onPause로 옮겼습니다!

2022-02-03 14:40 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/base/BaseActivity.kt
> +    val compositeDisposable = CompositeDisposable()
[f3a9a51](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/8/commits/f3a9a519fa7f10808a564ea0461e05d0f7de20f5)  밑에  binding변수에도 pretected 추가 하였습니다!

2022-02-03 14:41 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/base/BaseFragment.kt
> +        compositeDisposable.clear()
[7d8cada](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/8/commits/7d8cadaffd92762abc5fbbe547f9810f38ed00c8)  수정 커밋입니다~

2022-02-03 15:08 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/fragment/UserFragment.kt
> +                    userRepository.addFavoriteUser(searchedUser)?.subscribeOn(Schedulers.io())
[2d57953](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/8/commits/2d5795340af59b2fd294fd64d2aadb722a3cac6b)  수정 커밋입니다~

2022-02-03 15:13 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/fragment/UserFragment.kt
> +                        }?.subscribe()
[d5c492a](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/8/commits/d5c492a8c3b5e9ff1e92e8e14c6953799184960a). 수정 커밋입니다~

2022-02-03 15:46 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/fragment/UserFragment.kt
> +                            newList.map { user->
[ffc8715](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/8/commits/ffc8715c4f4a1cc169270e779474ffe43e0558e7) 수정하였습니다. !     튜터님  혹시  전혀 동작하지 않는 코드란 하신 이유는   map이 변경된 리스트를 리턴하는 것이지  리스트 객체 자체를  수정해주는것은 아니어서 인것이 맞을까요??

2022-02-03 16:02 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/fragment/UserFragment.kt
> +            .retry()
[6923fe9](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/8/commits/6923fe94f53a52db2ca95cb20f9bb6d36750078c). retry 횟수 2로 조건을 주었습니다!

2022-02-03 16:04 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/fragment/UserFragment.kt
> +        Single.zip(userRepository.getSearchUsers(binding.editSearchUser.text.toString(), page, perPage)
[34d8477](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/8/commits/34d84773718414a3cdca88f27c4a3d3772e7068b) 수정 커밋입니다~!

2022-02-03 16:06 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/fragment/UserFragment.kt
> +                remote.body()?.items.let { searUSerList->
[51ab645](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/8/commits/51ab645b84b60b87b9c7aadf894fec8b5bc3af56)  수정 커밋입니다~

2022-02-03 16:32 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/fragment/UserFragment.kt
> +                ?.observeOn(AndroidSchedulers.mainThread()),{
[691a1b1](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/8/commits/691a1b1e84453cc3d09b9b2815b1144d2ef3fadd)   뷰가 업데이트 되는 부분은  consumer 쪽으로 빼고 onSubscribe 위에  maitn thread 를 추가 했습니다.  나머지  io 부분및  가져온  값 수정 하는  로직은  schedulers.io 에서  진행하게 납두었습니다!

2022-02-03 16:41 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/model/SearchedUser.kt
> +    @PrimaryKey(autoGenerate = true) var uid: Long,//데이터 고유식별값 -> auto increment
[5f12e17](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/8/commits/5f12e17d1f9c02d51ca2a3377f1f40bb970e68a0) 수정 커밋입니다.!
그런데 nullbale한  처리는 왜  수정되어야 하는지 정확하게 이해하지 못했습니다 ;;ㅠㅠ

2022-02-03 16:44 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/repository/RepoRepository.kt
> +        userName:String = ""
[b7e3780](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/8/commits/b7e3780d1190e53166d2040c3405bacae38d26fa)  수정 커밋입니다~!

2022-02-03 16:50 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/repository/UserRepository.kt
> +interface UserRepository {
[37ab0b8](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/8/commits/37ab0b83d82e04ae23fe72156a116b1c637205e0)  수정 커밋입니다.!

2022-02-03 16:50 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/repository/UserRepositoryImpl.kt
> +    override fun deleteFavoriteUser(deletedFavoriteUser: SearchedUser):Completable? {
[37ab0b8](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/8/commits/37ab0b83d82e04ae23fe72156a116b1c637205e0)  수정 커밋입니다!

2022-02-03 16:54 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/source/local/UserLocalDataSource.kt
> +    fun addFavoriteUser(vararg favoriteUser:SearchedUser):Completable?//유저 즐겨찾기에 추가
[d83fe05](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/8/commits/d83fe057366f7ddfdf3cafbacb9044dfaac0b7b3) 수정 커밋입니다~!

2022-02-03 16:58 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/room/FavoriteMarkDataBase.kt
> +                        FavoriteMarkDataBase::class.java, "favoriteTable.db"
[bdc9b56](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/8/commits/bdc9b56fa12a2900d1cec465541119ce5db9f730) 수정 커밋입니다!

2022-02-03 23:08 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/activity/SplashActivity.kt
> +    override fun onResume() {
splash 화면은 정책에 따라 다르겠지만 backstack으로 두지 않아서 말씀드렸습니다. 보통 홈에서 뒤로가면 바로 그냥 메인에서 나가집니다. 
일단 알겠습니다~

2022-02-03 23:08 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/activity/SplashActivity.kt
> +            errorObservable.delay(3,TimeUnit.SECONDS).take(2)
chain 줄바꿈 해주세요

2022-02-03 23:12 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/activity/SplashActivity.kt
> +    private fun getGitHubUserInfo()=userRepository.getSearchUsers(query = "realizer12",1,10)
리포맷 항상 해주세요, default값은 의미가 뭔가요??

2022-02-03 23:12 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/fragment/FavoriteFragment.kt
> +    private lateinit var favoriteMarkedRcyAdapter: UserListRcyAdapter
변수명 바꿔주세요 Rcy라는 변수명은 잘 안씁니다.

2022-02-03 23:12 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/fragment/FavoriteFragment.kt
> +                    ?.subscribe()?.addTo(compositeDisposable)
nullable chaining

2022-02-03 23:12 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/fragment/FavoriteFragment.kt
> +        favoriteMarkedRcyAdapter.setFavoriteMarkClickListener(object:UserListRcyAdapter.FavoriteClickListener{
리포맷 해주세요

2022-02-03 23:12 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/fragment/UserFragment.kt
> +                        userListRcyAdapter.submitList(searchedUsersList!!.toMutableList())
!! 빼주세요

2022-02-03 23:12 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/fragment/UserFragment.kt
> +        }
이거 쓰는 이유가 뭔가요??

2022-02-03 23:57 UTC, sageHabitus requested changes

2022-02-03 23:57 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/adapter/RepoListRvAdapter.kt
> +class RepoListRvAdapter : ListAdapter<UserRepo, RepoInfoViewHolder>(diffUtil) {
RepoListRvAdapter와 UserRepoListAdapter를 하나로 합쳐주세요. 
하나로 재활용하시면 됩니다. 그래서 제가 과제 때 xml을 하나로 써달라는게 이 의미입니다.
DTO도 지금 단계에서 굳이 두개가 필요없어 보입니다.

2022-02-03 23:59 UTC, sageHabitus commented
Github PR Template 만들어주세요

2022-02-04 00:07 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/adapter/RepoListRvAdapter.kt
> +class RepoListRvAdapter : ListAdapter<UserRepo, RepoInfoViewHolder>(diffUtil) {
음 튜터님   UserRepoListAdapter는  검색된 유저와   즐겨찾기 한 유저들  화면에서   공통으로 사용하고 있고,
RepoListRvAdapter는 상세화면에서  특정 유저의  레포지토리 목록들을 뿌려줄때 사용하고 있습니다. 
둘이  아이템 뷰 구성도 다른데   합쳐야 하는 이유가 있을까요??

2022-02-04 00:11 UTC, sageHabitus commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/adapter/RepoListRvAdapter.kt
> +class RepoListRvAdapter : ListAdapter<UserRepo, RepoInfoViewHolder>(diffUtil) {
아아 착각했습니다 죄송합니다

2022-02-04 00:14 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/adapter/RepoListRvAdapter.kt
> +class RepoListRvAdapter : ListAdapter<UserRepo, RepoInfoViewHolder>(diffUtil) {
아 넵넵 아닙니다!   네이밍이 좀  헷갈리게  구성되었던거 같습니다 ㅎㅎㅎ;;;

2022-02-04 00:15 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/fragment/UserFragment.kt
> +        }
아이고 이거 어제  ->  zip. 관련해서   수정 하다가   에러 나오면서 죽길래  잠깐 추가했었는데  
제거를 안했네요;;   수정해놓겠습니다.

2022-02-04 09:57 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/room/FavoriteMarkDataBase.kt
> +        fun getInstance(context: Context): FavoriteMarkDataBase? {
[818f9bf](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/8/commits/818f9bf6a35f3b7ac594e3def372a4e3c5acba36). 수정 커밋입니다.!!   맞게 적용되었는지는 잘모르겠습니다;;

2022-02-04 09:58 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/source/local/UserLocalDataSourceImpl.kt
> +class UserLocalDataSourceImpl(private val favoriteDao: FavoriteDao?):UserLocalDataSource {
[974062d](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/8/commits/974062d57056fb22fe1d3a360ed216f4383fa119) 수정 커밋입니다!

2022-02-04 10:00 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/source/local/UserLocalDataSourceImpl.kt
> +    override fun getFavoriteUsers(): Single<List<SearchedUser>>? = favoriteDao?.getFavoriteGitUsers(true)
[37ab0b8](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/8/commits/37ab0b83d82e04ae23fe72156a116b1c637205e0)  수정 커밋입니다!   nullable 하지 않게 수정 하였습니다!

2022-02-04 10:03 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/source/remote/RepoRemoteDataSource.kt
> +    ): Single<ArrayList<UserRepo>>
[6e137b5](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/8/commits/6e137b595cfdec318ea001f2d30f1373f9a87bf1) 수정 커밋입니다!

2022-02-04 10:04 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/source/remote/RepoRemoteDataSourceImpl.kt
> +    ): Single<ArrayList<UserRepo>> {
[6e137b5](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/8/commits/6e137b595cfdec318ea001f2d30f1373f9a87bf1)수정 커밋입니다!

2022-02-04 10:06 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/source/remote/UserRemoteDataSource.kt
> +        query:String = "",
[b7e3780](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/8/commits/b7e3780d1190e53166d2040c3405bacae38d26fa)  수정 커밋입니다~!

2022-02-04 10:10 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/repository/UserRepositoryImpl.kt
> +    override fun addFavoriteUser(vararg favoriteUser: SearchedUser):Completable? {
[1b5d84d](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/8/commits/1b5d84d238027242cb63f4fcfc59976518972a92)  수정 커밋 입니다~!

2022-02-04 10:14 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/room/FavoriteDao.kt
> +    fun deleteFavoriteUser(userId:Long?):Completable
[752b0db](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/8/commits/752b0db52dda8d1002509663721c711a926df82a) 수정 커밋입니다~!

2022-02-04 10:16 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/room/FavoriteDao.kt
> +    fun getFavoriteGitUsers(isMyFavorite:Boolean): Single<List<SearchedUser>>
[1413127](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/8/commits/1413127f34e9ca3c92112b2023b492e33cded46a) 수정 커밋입니다~!

2022-02-04 10:24 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/room/FavoriteMarkDataBase.kt
> +                synchronized(FavoriteMarkDataBase::class) {//중복생성  방지
[1440e5c](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/8/commits/1440e5c2cac3ec868a5ff0e0cf23380343f659c6) 수정 커밋입니다!

2022-02-04 10:26 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/viewholder/UserViewHolder.kt
>      fun bind(searchedUser: SearchedUser){
[fb4ec98](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/8/commits/fb4ec980a9117b91c82548a910b5c86968a059e3) 수정 커밋입니다~

2022-02-04 10:31 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/source/remote/UserRemoteDataSourceImpl.kt
> +       return RetrofitHelper.apiServices.searchUsers(query, page, perPage)
[5dbe82d](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/8/commits/5dbe82db5f779f2ed4c4e454361d661d9a75b395) 수정 커밋 입니다~!

2022-02-04 10:35 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/fragment/UserFragment.kt
> +            userRepository.getFavoriteUsers()?.subscribeOn(Schedulers.io())
[2d57953](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/8/commits/2d5795340af59b2fd294fd64d2aadb722a3cac6b) 수정 커밋입니다~!

2022-02-04 10:42 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/fragment/UserFragment.kt
> +                        }?.subscribe()
[d5c492a](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/8/commits/d5c492a8c3b5e9ff1e92e8e14c6953799184960a). 수정 커밋입니다~!

2022-02-04 10:45 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/fragment/UserFragment.kt
> +                        ?.observeOn(AndroidSchedulers.mainThread())
[0e512bb](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/8/commits/0e512bbf16b2b71a6f95294981fd14567ee845c8) 수정 커밋입니다~!

2022-02-04 10:47 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/activity/SplashActivity.kt
> +            errorObservable.delay(3,TimeUnit.SECONDS).take(2)
[0b8d488](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/8/commits/0b8d488950dab8c4f9675be16a12f6bcc6448986) 수정 커밋입니다~!

2022-02-04 10:50 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/activity/SplashActivity.kt
> +    private fun getGitHubUserInfo()=userRepository.getSearchUsers(query = "realizer12",1,10)
[0b67983](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/8/commits/0b67983c7083b61530d47a8e964ac8bf5e849bc4)  리포맷 적용 하였습니다!

default값은  splash 에서  유저정 보를  가져와서  메인으로 넘기는데 ,
이때  고정적으로  제  깃헙 정보를  받아와서  메인에  뿌려지도록  코드를 짜 놓았습니다!

2022-02-04 10:54 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/fragment/FavoriteFragment.kt
> +    private lateinit var favoriteMarkedRcyAdapter: UserListRcyAdapter
[ce27bae](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/8/commits/ce27baeaafb725b9ab3ef2f8ebd98e7e80f52288) 수정 커밋입니다~!

2022-02-04 10:58 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/fragment/FavoriteFragment.kt
> +                    ?.subscribe()?.addTo(compositeDisposable)
[e30a763](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/8/commits/e30a763a72f1c6047925648227525f5f1839384c) 수정 커밋입니다~!

2022-02-04 10:59 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/fragment/FavoriteFragment.kt
> +        favoriteMarkedRcyAdapter.setFavoriteMarkClickListener(object:UserListRcyAdapter.FavoriteClickListener{
[06d6d27](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/8/commits/06d6d27007774524e545c65ed338c4e2e021997e) 수정 커밋입니다~!

2022-02-04 11:01 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/fragment/UserFragment.kt
> +        }
[7cf4edb](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/8/commits/7cf4edbf3ab156d057c86a8b132f5e944dc562cd) 수정 커밋 입니다~!

2022-02-04 12:15 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/viewholder/UserViewHolder.kt
> +        if (searchedUser.isMyFavorite) {
[abf6387](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/8/commits/abf6387186c30726c3451a6ef4f014809fe578a1) 수정 커밋 입니다~!

2022-02-04 12:44 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/fragment/UserFragment.kt
> +                    userListRcyAdapter.notifyDataSetChanged()//전체 업데이트가 안되어서 이렇게 notify넣어줌.
튜터님  이부분은    즐겨찾기 fragment에서  다시 별표 취소하고,  유저 프래그먼트 탭으로 돌아왔을때   새로 submitlist에 넘겨주는 newList에는  값이 바껴있는데
별표 뷰가 업데이트 되지않아   추가했었습니다.;;
submitList 넣을때 분명  변경된   아이템을  넣어준거 같은데   왜  뷰가 업데이트가 안될까요?? ㅠㅠ

2022-02-04 12:45 UTC, realizer12 commented on 20220122_realizer12/presentation/src/main/java/com/example/presentation/fragment/UserFragment.kt
> +                            userListRcyAdapter.notifyItemChanged(position)
위  serListRcyAdapter.notifyDataSetChanged() 문제와 같은 문제입니다;;

2022-02-05 03:32 UTC, realizer12 commented
[b570662](https://github.com/AndroidTutoring/Android_CleanArchitecture_Tutoring/pull/8/commits/b570662caa057ca9630edaff69707ea426233f90)  전체적인 코드 리포맷팅 추가하였습니다!

2022-02-05 03:51 UTC, sageHabitus approved these changes

2022-02-05 03:51 UTC, merged